### ISSUE TITLE
Full application deployment crash

### ISSUE THREAD

**Issue by Nuvey81** [GreenWaves-Technologies/occupancy_management#3]
Hello,
I tried to run the application in full deployment (thermEye capture + BLE + android APK) but unfortunately, it was not working properly. Indeed, after few iteration, the application is "Frozen": nothing appears on the logs and the recognition no seems to work.

I think the problem is on the cluster call. Something should not be clear properly and the memory is full.

I solved this problem with a less optimal solution: i just create a _pi_device_ and a _pi_cluster_ in the loop of the _peopleDetection_ function. After that, i open the cluster and call the graph constructor (_lynredCNN_Construct_ function). The rest of the loop does not change except in the end where i destruct the CNN (_lynredCNN_Destruct_ function) and close the cluster (_pi_cluster_close_ function). With this, the application works ant does not crash. 

So i am wondering if anyone have the same problem in a full application deployment. If so, can my solution temporarily works ?

Thanks a lot.

NB: I use the GAPoC_b_2.3 with the 3.6.1_dev SDK.

**Comment by Pafrak** [comment]
Indeed, in release 3.7 we found a regression, that we will fix asap.

I'll keep you posted.

**Comment by Pafrak** [comment]
This has been fixed with latest drop, please let us know if you are still experiencing issues.
